export const aiModels = {
  mistral: [
    "mistral-codestral-25.01",
    "mistral-large-2",
    "mistral-nemo",
    "mistral-codestral",
    "mistral-7B-Instruct-v0.1",
    "mixtral-8x7B",
    "mistral-7B-Instruct-v0.2",
  ],
  deepSeek: ["deepseek-v3"],
  openAi: ["o1", "gpt-4", "o1-preview", "o1-mini", "gpt-4o", "gpt-4o-mini"],
  google: [
    "gemini-2.0-flash",
    "gemini-1.5-flash-8B",
    "gemini-1.5-flash",
    "gemini-1.5-pro",
  ],
  meta: [
    "Llama-3.3-70B",
    "Llama-2-13B",
    "Llama-3-8B",
    "Llama-3-70B",
    "Llama-3.2-3B",
    "Llama-3.2-1B",
    "Llama-3.1-70B-Instruct",
    "Llama-3.1-8B-Instruct",
    "Llama-3.1-405B-Instruct",
  ],
  anthropic: [
    "claude-3.5-haiku",
    "claude-3-sonnet",
    "claude-3-haiku",
    "claude-3-opus",
    "claude-3.5-sonnet",
  ],
  xAi: ["grok-beta"],
  cohere: ["command-r", "command-r-plus"],
};
